"""empty message

Revision ID: 4cc077eb0167
Revises: 085ba2defef5
Create Date: 2025-03-27 14:55:45.783601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cc077eb0167'
down_revision = '085ba2defef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sos_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sos_message', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
