"""empty message

Revision ID: bc432806b225
Revises: 4cc077eb0167
Create Date: 2025-03-29 17:02:07.201105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc432806b225'
down_revision = '4cc077eb0167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sos_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('disaster_type', sa.String(length=100), nullable=True))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sos_message', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('disaster_type')
        batch_op.drop_column('mobile_number')

    # ### end Alembic commands ###
